name = "mergeable-backend"
compatibility_date = "2024-08-21"
main = "./src/index.ts"

[observability.logs]
enabled = true
invocation_logs = true

[vars]
MERGEABLE_HOST_URL = "https://mergeable.pages.dev"