name = "mergeable-backend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./src/index.ts"

[observability.logs]
enabled = true
invocation_logs = true

[vars]
MERGEABLE_HOST_URL = "https://app.usemergeable.dev"