---
name: helm-publish
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package chart
        run: helm package production/helm/reviewer --version 0.0.${{ github.run_number }} --destination dist
      - name: Push chart to GHCR
        run: helm push dist/*.tgz oci://ghcr.io/pvcnt/helm |& tee .digest
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
      - name: Sign chart
        env:
          HELM_EXPERIMENTAL_OCI: 1
          COSIGN_EXPERIMENTAL: 1
        run: cosign sign --yes ghcr.io/pvcnt/helm/reviewer@$(cat .digest | awk -F "[, ]+" '/Digest/{print $NF}')
